### ISSUE TITLE
dice roller

### ISSUE THREAD

**Issue by shindakun** [shindakun/cautious-waffle#74]
roll for initiviteeee

roll x number of dice and return value

`/waffle roll 2d20`

also take into consideration the character bonuses etc

**Comment by shindakun** [comment]
`7 + 7 = 14`

**Comment by CharlesAMoss** [comment]
close this ... it has been merged @shindakun

**Comment by shindakun** [comment]
@CharlesAMoss pro tip if you submit a pr that closes something add the line

`closes #{{issue_number}}` like:

closes #74
