### ISSUE TITLE
slash command throws http_service_error for subcmd it doesn't recognize

### ISSUE THREAD

**Issue by quandrum** [shindakun/cautious-waffle#9]
AT
/waffle whooo

er
NOOP

ar
http_service_error

**Comment by shindakun** [comment]
![Screen Shot 2020-03-20 at 8 36 33 PM](https://user-images.githubusercontent.com/319128/77218629-8b4a1100-6aea-11ea-9a08-3f87b51c143a.png)

**Comment by Eve1994** [comment]
hi have you found a fix for this http_service_error ... I am new to git so not sure how to access the fix ... I keep getting a http_service_error when typing in my slash command into slack... I am using python
